apiVersion: v1
kind: ConfigMap
metadata:
  name: subs-nginx
  namespace: subs
data:
  default.conf: "server {\n  listen 8080;\n  server_name _;\n\n  error_page 404 =\
    \ @notfound;\n  location @notfound {\n    default_type text/html;\n    return\
    \ 404 '<html><head><title>404 Not Found</title></head><body><center><h1>404 Not\
    \ Found</h1></center><hr><center>nginx</center></body></html>';\n  }\n\n  location\
    \ /sub/ {\n    alias /srv/sub/;\n    default_type text/plain;\n    add_header\
    \ profile-title \"base64:aXBxdw==\" always;\n    add_header profile-update-interval\
    \ \"12\" always;\n    add_header subscription-userinfo \"upload=0; download=0;\
    \ total=0; expire=0\" always;\n    add_header routing \"happ://routing/add/eyJOYW1lIjogIiIsICJHbG9iYWxQcm94eSI6ICJ0cnVlIiwgIlJvdXRlT3JkZXIiOiAiYmxvY2stcHJveHktZGlyZWN0IiwgIlJlbW90ZUROU1R5cGUiOiAiRG9IIiwgIlJlbW90ZUROU0RvbWFpbiI6ICJodHRwczovL2Nsb3VkZmxhcmUtZG5zLmNvbS9kbnMtcXVlcnkiLCAiUmVtb3RlRE5TSVAiOiAiMS4xLjEuMSIsICJEb21lc3RpY0ROU1R5cGUiOiAiRG9VIiwgIkRvbWVzdGljRE5TRG9tYWluIjogIiIsICJEb21lc3RpY0ROU0lQIjogIiIsICJHZW9pcHVybCI6ICIiLCAiR2Vvc2l0ZXVybCI6ICIiLCAiTGFzdFVwZGF0ZWQiOiAiIiwgIkRuc0hvc3RzIjogeyJjbG91ZGZsYXJlLWRucy5jb20iOiAiMS4xLjEuMSJ9LCAiRGlyZWN0U2l0ZXMiOiBbImdlb3NpdGU6Y2F0ZWdvcnktcnUiLCAicmVnZXhwOi4qXFwucnUiLCAiZ2Vvc2l0ZTp5YW5kZXgiLCAiZ2Vvc2l0ZTptYWlscnUiLCAiZ2Vvc2l0ZTphcHBsZSIsICJnZW9zaXRlOm1pY3Jvc29mdCIsICJnZW9zaXRlOmdvb2dsZS1wbGF5Il0sICJEaXJlY3RJcCI6IFsiZ2VvaXA6cHJpdmF0ZSIsICJnZW9pcDpydSJdLCAiUHJveHlTaXRlcyI6IFtdLCAiUHJveHlJcCI6IFtdLCAiQmxvY2tTaXRlcyI6IFsiZ2Vvc2l0ZTpjYXRlZ29yeS1hZHMtYWxsIl0sICJCbG9ja0lwIjogW10sICJEb21haW5TdHJhdGVneSI6ICJJUElmTm9uTWF0Y2giLCAiRmFrZUROUyI6ICJmYWxzZSIsICJVc2VDaHVua0ZpbGVzIjogInRydWUifQ==\"\
    \ always;\n    add_header cache-control \"no-store\" always;\n  }\n\n  location\
    \ = / { return 404; }\n}\n"
