apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:G0KJkReFWeSd5fnwNfCm+CHlT8gM+sjCHuVl3u69opZd5zzXrHgMSS9gh4+hJ6+YSXUTSIUk1luSCOZVCjenvXSmnMtQOhoupTApwoVkEx2HaZ6mcoYXqXflMvI27jKDT5dyWMlk2g1/eNK+oEZ0rpI5Y0LMp5zCHLhD3WsUv54=,iv:YF1jUzSs3PHXMNumMENHqcvebK6fsTJVguPQ5rU9AQU=,tag:MRjtSAToNFRZjS7jYmbWjg==,type:str]
kind: Secret
metadata:
    name: ghcr-pull
    namespace: whitelist-bypass
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4NFpUeDlHQUxOeVJjNDJ4
            OEppRHFmTkx3end6T2xjT21ZWk1UVFh4dUJjCjc3QmlNTGJ0cG5RQzlNZFZaSVdo
            Sk5TNDhtWXdBQkJ2RGo3bTh6bVdqZVkKLS0tIEtoeFdkQXo5OXVSRm9MaFN2dkMv
            ZkdreXN6KzRiNnZpck4wOGxYSGtZdjQKyt2MBqojrh+2eEk1S5xFrKp7vggUMDnW
            zuGUECKdBpziCRKEaPwfc+MoSjGF+I85K6VcNpYQLyKAa7hjHV7L+g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fnteet2mnkw75uhpz4k0nzwdxjwcxyy5ludtkx55w2afvm98yg6q6jc8r6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-22T17:36:00Z"
    mac: ENC[AES256_GCM,data:LVtt8D7HxDT4rmPDGzrSdgNTReV83rfF0QmToKUitlaRWVRHeNHmdpw/uUs7QWm1hPj17iRNmtV80BOviysDGkdn4Zhlp/rUIEw0xXQDjo5WcY/B1ZdtQS6ajkqkEHWNUORFLtt++VNLDf4FfBVPLgnCXB3QJ0TQ6TpEeiaMxoo=,iv:Ds6c0u+wpPFj+xm5bXhq1VSIY0nvYlZBdTBwfK1eGoo=,tag:8/i46XXW+hJsEAKsMs0fYQ==,type:str]
    version: 3.13.3
