apiVersion: v1
data:
    VK_GROUP_ID: ENC[AES256_GCM,data:3zqHM4jv0Hcej/jp,iv:muRDlch9/wnJb6rz9lr1+k1DAU3P+l780gniLvdtt44=,tag:9AmN3VIXeJcr+hfI2H/Djg==,type:str]
    VK_TOKEN: ENC[AES256_GCM,data:JzqZJUr9mqHy3PSeNkxbgUgWv+yE7ckyispBugJEliXHIOnHx41CZOrlW2o1WSO8ygsjixNS/FMjK6KeLMvjPEI+tIScG+GHENHHiQIZpYNoM5SOAasPvml8FHa+Y1aVUTzNDWJrM08pmilqNiPi4aF4gsSXt1K3oHOAxF0k0aPBj2xWkRC2OoMJrardAlkh8/Pk/rqmz7Qg/O2ZYmgRue96dfqQz+4e5AKdpqhtmRhUUAfOa993x0NKcFSqZ5O/eLt6KYCxaOUMLhvrPotHDmUqS5cfY3Dk2gzAnpFN4Z4f+k+lwHYW1AcW63xVerMyA4Ia/B6Fh/nt5Y3YDlGy10P6nY9X8By7DkGX3jYDBdNVuHnzYU5zzZauwFYZeiDZ6i5WgjfsDgA=,iv:5Qe3A+oqBa/pDASr2V55HtQJpzW8dCa6ap5zwwUyfnE=,tag:pmKG/gLO2GvrtUlwRTP25w==,type:str]
kind: Secret
metadata:
    name: whitelist-bypass-vk
    namespace: whitelist-bypass
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRMDVvTDkwOWRjd1BtZUVt
            RUZlc1JYeGcwNnEzRWlXYTZobHRxbFNNSGdZCmZ3MnRLdHpocTBQZVBEUEN3V2tK
            cXV2UHBQMmo5TUpoa0FubDNDUmcwOTAKLS0tIEFGSmM2TjhncVl3Z0dwVjdBYjdi
            SDJhdWZNOXRSTDU0TnVYQlYwNTNTMWcKuc990GwWnU3pRvGAnqx/9IheRiTIa8qS
            oUF5w0tAUWvj8cFvdb2biHfpCLOvz1Wx4zqJuZG/+ILJqCBSUbVGjA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fnteet2mnkw75uhpz4k0nzwdxjwcxyy5ludtkx55w2afvm98yg6q6jc8r6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-22T17:35:52Z"
    mac: ENC[AES256_GCM,data:g1qmU16x81uISEb7YBpVV+KN3H/XsjooyNq+kg3ai+MDd1tSREsQgTyCwsGz2UYLgONlnp/dOLbb85/1rhmqEKbVhWMjPbnistzJQQZAHNg11XmCpvTRgQB1jcSkc26pEqCmbJTBqI9G8lXyvewnJE8R3p5DXygo4YZyGOXnASI=,iv:mVIwQsiZNrA+1KhmNjW7mUGk4uUovikRRoaR++RJ/wQ=,tag:mDOcwSrItn3jB1fAoJ53Mg==,type:str]
    version: 3.13.3
