apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:A9xNgytAGk0J4Z+UH8anT6YlvW/ofgaj/iSxLlx7mXzKF+2LwInGzrA4OMeM8Fz6Tr2ptZW2rbfxkvSpvG+r4G0dqUok2zjSpdMS5Jbu0tR236HByBC7GrtPxXoM9QWRDM7/Yvui8QdBBXx6x2zzI9xWmGFF14fQ1LOLNAypPbW6LlQMeWnb9Lii+3xi93rOQf5oUymMvrGQ1Tjqfuil9U64M9/aTPolVa0RYzDFJE7zcmKP/uosUu3QvzTPGDXlB9KHGbkti1jcQ0In+J3iLeIkGRSkbcpmKTTD1Q==,iv:L4+jICFkWXs0qXtJhkesjjYQ+bZGfIGZYo37BvubioU=,tag:uYbkrkHv1WaTEFA2ZjcacQ==,type:str]
kind: Secret
metadata:
    name: ghcr-pull
    namespace: whitelist-bypass
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtcnhROEdrY0pjU05JdUJt
            NzhsMHBlSnl0L09sckovWmhqanBqc2JaYkFjCjE5M2c0SHJydnZpbEI0RnVuVDlZ
            em82ZWpHc0VjMXdOOFl2Z3RHcGg4ek0KLS0tIGd6NDkraDFwQjc0QnZHZnhJb1lh
            L3QwbUFiblkzSHc3eXhuWXFYcHhLY0EKZwsZeRVfSQx0AejVLg+GKadpg9f7cnYX
            p8BuLqNOBITuoeXBAI3Y9m09kfQzHAiOxRa2eTjd6c6X2ybed7bPBg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fnteet2mnkw75uhpz4k0nzwdxjwcxyy5ludtkx55w2afvm98yg6q6jc8r6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-22T17:52:04Z"
    mac: ENC[AES256_GCM,data:O6ZbfXWmnrG4UkD3gNkwO5KZleC4e4zzcVmQ7DHPKplYDF0DL/ubRwjj2N8g6v7xaYTZ7DGXx7vV4Q58K+Z6yEm2//Cts+SexSWeXeFfIHSHFC9xZRUzgUvfkFdo3iR02vyzORUeLkgnds6oUcMGi1fi4yXaq9bfijKXmpezfYY=,iv:1CBWJfIo/f7csh9Ppdt/u5YaBYWmC2ORVzB5zbu/Mrk=,tag:vdfr3+1tanZuVCJXkqm0Rg==,type:str]
    version: 3.13.3
