# Префикс пути — фактический пароль туннеля. Сервер отвечает только на
# WebSocket-апгрейд по этому пути; всё остальное на wg.ipqw.cc traefik
# отдаёт как обычный 404, и домен выглядит пустым сайтом.
apiVersion: v1
kind: Secret
metadata:
    name: wstunnel-auth
    namespace: wstunnel
type: Opaque
stringData:
    path-prefix: ENC[AES256_GCM,data:RXjoto9heJRj8laDB55NNc45bTU+AfrC,iv:XubJm18YPFFaoWiPx6sReKEvFWkpWZ3E8sZWFEp6oeg=,tag:ouzBvDTArY7uhM9dqYj9Nw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5R2FkMjdlU09pR2xEY09R
            aFgyQmpOMzFRR0tHY0VUTmpOWU9KdGRwWVZBCmpCd25ITTJnZzVwdlZFeTlTclFu
            L2JjVFNFd3NKUXVUT1pTMGZ6V3QyZmMKLS0tIGUrdmxubG5ZZVFLRVF6RUdRMm1G
            ZWU2RGVMdHk3d3NYSzZBdTErOXkxQ1kKQjCnAack54ORmtdo2ptEBuo0dNI6tJtC
            0wYADeem6J0QYR4jJNGAitVuETCeewJE6Hbrhi7Nh8Omaa14Us3cQg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fnteet2mnkw75uhpz4k0nzwdxjwcxyy5ludtkx55w2afvm98yg6q6jc8r6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-24T13:26:28Z"
    mac: ENC[AES256_GCM,data:NhbMu9ntht2IMrrxweMcsTVL/333G1CcC9JBt8uGIAZ6yYbpU8dy4SuUz6l8WMIJwwTKlKA4IDYqKrtOvRdCcdF4UfdV4Tcdc4vqIwy4C0iJd7kCxECdT83vNoeUBXR9A1hMsS/E3P+FdWyVabRzj9bdTK0zto4lyzIVohGT4Hg=,iv:T0Q3m5Q4NtcO7ax+yxw/q/aIHP4/yN+EPJkWK/7u1lw=,tag:QAHvkriV/roOmYbsWofAzA==,type:str]
    version: 3.13.3
