apiVersion: v1
kind: Secret
metadata:
    name: cloudcli-telegram
    namespace: cloudcli
stringData:
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:91nwB+aitGj3D3DoQh6kYVHTv+RAEz3C4vhr44NRzoBdWO7e4muFzQWbAHdCwA==,iv:izvrziWY2agTOfE6fM9ZSmvkbjMNA8PloqTTgY9gBvY=,tag:VNr2/NXx2mlu4SuHAtp3AQ==,type:str]
    ALLOWED_USERS: ENC[AES256_GCM,data:sj2bqAZhPR4Low==,iv:UdHQq3/y+Eq1OCKuSwwoiPTSHY2w/qAzxea/3RkAbo0=,tag:cozqQZbfeR23DIoCKLuUhg==,type:str]
    CLOUDCLI_USERNAME: ENC[AES256_GCM,data:VHva+g==,iv:2lWw2qMHUtNIf7WlXlduCIwvwVGBdCNxoha/4usVDgE=,tag:iLRtT+hQar5G+4eyk7USJQ==,type:str]
    CLOUDCLI_PASSWORD: ENC[AES256_GCM,data:s0EjQK2lwKHGImUzqPwv,iv:wHwsXCk8Hon2Aq2TsqJM9HsBvPqi+2Ih4Opi7UY/LAg=,tag:Iez4RPhLaFUaeX6dupAwkQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKMkxma0UrMFJCNmJtTnZI
            Nnl5RDRwNzNsL1lxR1pWWVVocWJOeTcvckQ4Cm5tcktjam5ta3l4TWZCdlNJYjRp
            ZlVZWTJISElxWTE2QU5Qcnl5S3lMT28KLS0tIHBrQi9GQmpLUUxrL2hteXl6Uzdy
            MmxGd3dLcCtGeGVJQWt6eGRkTU94SDgKvcJVHyMY3LRjLSlctuQgP55wvf9jVTJm
            fG2xDRdWKcINpVeP9z+6bDasbE9bTVsKQu55sk+PCZ0bTUbEUQbswQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fnteet2mnkw75uhpz4k0nzwdxjwcxyy5ludtkx55w2afvm98yg6q6jc8r6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-01T17:06:09Z"
    mac: ENC[AES256_GCM,data:EiYnaUSdiirFhhE1YIUP+SeOqRvquXnLsVqGEnGUQ5quK7tBQFSn4HwJivPeBslU8Oh0F5BzRjqyzJW0h8wEiyeE9GeYWzJ6BQvPcnXQfeLJMMfkaHBULJN8lUiw4jmi+sntOJIu9IBR++ZIWgPWy3wfWi+gL8YI0UMUnIiCKm4=,iv:UgOqjhcWOs5lGYRlWG+/iZ9f5u/OFguC0ZW5Z8Q2iiM=,tag:hcr3Om9tpWlKv3pSCkizrA==,type:str]
    version: 3.13.3
